/*
 * generated by Xtext
 */
package org.example.xbase.entities;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntitiesRuntimeModule extends org.example.xbase.entities.AbstractEntitiesRuntimeModule {

}
