/*
 * generated by Xtext
 */
package org.example.xbase.entities.ui.contentassist

import org.example.xbase.entities.ui.contentassist.AbstractEntitiesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
