/*
* generated by Xtext
*/
package org.example.smalljava.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.smalljava.services.SmallJavaGrammarAccess;

public class SmallJavaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SmallJavaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.example.smalljava.parser.antlr.internal.InternalSmallJavaParser createParser(XtextTokenStream stream) {
		return new org.example.smalljava.parser.antlr.internal.InternalSmallJavaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SJProgram";
	}
	
	public SmallJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmallJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
