/*
 * generated by Xtext
 */
package org.example.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.example.expressions.ui.hover.ExpressionsEObjectHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpressionsUiModule extends org.example.expressions.ui.AbstractExpressionsUiModule {
	public ExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return ExpressionsEObjectHoverProvider.class;
	}
}
