/**
 * generated by Xtext
 */
package org.example.xbase.entities.validation;

import org.example.xbase.entities.validation.AbstractEntitiesValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EntitiesValidator extends AbstractEntitiesValidator {
}
