/*
* generated by Xtext
*/
package org.example.smalljava.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.example.smalljava.services.SmallJavaGrammarAccess;

public class SmallJavaParser extends AbstractContentAssistParser {
	
	@Inject
	private SmallJavaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.example.smalljava.ui.contentassist.antlr.internal.InternalSmallJavaParser createParser() {
		org.example.smalljava.ui.contentassist.antlr.internal.InternalSmallJavaParser result = new org.example.smalljava.ui.contentassist.antlr.internal.InternalSmallJavaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSJMemberAccess().getAlternatives(), "rule__SJMember__Alternatives");
					put(grammarAccess.getSJStatementAccess().getAlternatives(), "rule__SJStatement__Alternatives");
					put(grammarAccess.getSJIfBlockAccess().getAlternatives(), "rule__SJIfBlock__Alternatives");
					put(grammarAccess.getSJBlockAccess().getAlternatives(), "rule__SJBlock__Alternatives");
					put(grammarAccess.getSJSymbolAccess().getAlternatives(), "rule__SJSymbol__Alternatives");
					put(grammarAccess.getSJTerminalExpressionAccess().getAlternatives(), "rule__SJTerminalExpression__Alternatives");
					put(grammarAccess.getSJTerminalExpressionAccess().getValueAlternatives_2_1_0(), "rule__SJTerminalExpression__ValueAlternatives_2_1_0");
					put(grammarAccess.getSJAccessLevelAccess().getAlternatives(), "rule__SJAccessLevel__Alternatives");
					put(grammarAccess.getSJProgramAccess().getGroup(), "rule__SJProgram__Group__0");
					put(grammarAccess.getSJProgramAccess().getGroup_0(), "rule__SJProgram__Group_0__0");
					put(grammarAccess.getSJImportAccess().getGroup(), "rule__SJImport__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getSJClassAccess().getGroup(), "rule__SJClass__Group__0");
					put(grammarAccess.getSJClassAccess().getGroup_2(), "rule__SJClass__Group_2__0");
					put(grammarAccess.getSJFieldAccess().getGroup(), "rule__SJField__Group__0");
					put(grammarAccess.getSJMethodAccess().getGroup(), "rule__SJMethod__Group__0");
					put(grammarAccess.getSJMethodAccess().getGroup_4(), "rule__SJMethod__Group_4__0");
					put(grammarAccess.getSJMethodAccess().getGroup_4_1(), "rule__SJMethod__Group_4_1__0");
					put(grammarAccess.getSJParameterAccess().getGroup(), "rule__SJParameter__Group__0");
					put(grammarAccess.getSJMethodBodyAccess().getGroup(), "rule__SJMethodBody__Group__0");
					put(grammarAccess.getSJStatementAccess().getGroup_2(), "rule__SJStatement__Group_2__0");
					put(grammarAccess.getSJReturnAccess().getGroup(), "rule__SJReturn__Group__0");
					put(grammarAccess.getSJVariableDeclarationAccess().getGroup(), "rule__SJVariableDeclaration__Group__0");
					put(grammarAccess.getSJIfStatementAccess().getGroup(), "rule__SJIfStatement__Group__0");
					put(grammarAccess.getSJIfStatementAccess().getGroup_5(), "rule__SJIfStatement__Group_5__0");
					put(grammarAccess.getSJIfBlockAccess().getGroup_1(), "rule__SJIfBlock__Group_1__0");
					put(grammarAccess.getSJAssignmentAccess().getGroup(), "rule__SJAssignment__Group__0");
					put(grammarAccess.getSJAssignmentAccess().getGroup_1(), "rule__SJAssignment__Group_1__0");
					put(grammarAccess.getSJSelectionExpressionAccess().getGroup(), "rule__SJSelectionExpression__Group__0");
					put(grammarAccess.getSJSelectionExpressionAccess().getGroup_1(), "rule__SJSelectionExpression__Group_1__0");
					put(grammarAccess.getSJSelectionExpressionAccess().getGroup_1_3(), "rule__SJSelectionExpression__Group_1_3__0");
					put(grammarAccess.getSJSelectionExpressionAccess().getGroup_1_3_1(), "rule__SJSelectionExpression__Group_1_3_1__0");
					put(grammarAccess.getSJSelectionExpressionAccess().getGroup_1_3_1_1(), "rule__SJSelectionExpression__Group_1_3_1_1__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_0(), "rule__SJTerminalExpression__Group_0__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_1(), "rule__SJTerminalExpression__Group_1__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_2(), "rule__SJTerminalExpression__Group_2__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_3(), "rule__SJTerminalExpression__Group_3__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_4(), "rule__SJTerminalExpression__Group_4__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_5(), "rule__SJTerminalExpression__Group_5__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_6(), "rule__SJTerminalExpression__Group_6__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_7(), "rule__SJTerminalExpression__Group_7__0");
					put(grammarAccess.getSJTerminalExpressionAccess().getGroup_8(), "rule__SJTerminalExpression__Group_8__0");
					put(grammarAccess.getSJProgramAccess().getNameAssignment_0_1(), "rule__SJProgram__NameAssignment_0_1");
					put(grammarAccess.getSJProgramAccess().getImportsAssignment_1(), "rule__SJProgram__ImportsAssignment_1");
					put(grammarAccess.getSJProgramAccess().getClassesAssignment_2(), "rule__SJProgram__ClassesAssignment_2");
					put(grammarAccess.getSJImportAccess().getImportedNamespaceAssignment_1(), "rule__SJImport__ImportedNamespaceAssignment_1");
					put(grammarAccess.getSJClassAccess().getNameAssignment_1(), "rule__SJClass__NameAssignment_1");
					put(grammarAccess.getSJClassAccess().getSuperclassAssignment_2_1(), "rule__SJClass__SuperclassAssignment_2_1");
					put(grammarAccess.getSJClassAccess().getMembersAssignment_4(), "rule__SJClass__MembersAssignment_4");
					put(grammarAccess.getSJFieldAccess().getAccessAssignment_0(), "rule__SJField__AccessAssignment_0");
					put(grammarAccess.getSJFieldAccess().getTypeAssignment_1(), "rule__SJField__TypeAssignment_1");
					put(grammarAccess.getSJFieldAccess().getNameAssignment_2(), "rule__SJField__NameAssignment_2");
					put(grammarAccess.getSJMethodAccess().getAccessAssignment_0(), "rule__SJMethod__AccessAssignment_0");
					put(grammarAccess.getSJMethodAccess().getTypeAssignment_1(), "rule__SJMethod__TypeAssignment_1");
					put(grammarAccess.getSJMethodAccess().getNameAssignment_2(), "rule__SJMethod__NameAssignment_2");
					put(grammarAccess.getSJMethodAccess().getParamsAssignment_4_0(), "rule__SJMethod__ParamsAssignment_4_0");
					put(grammarAccess.getSJMethodAccess().getParamsAssignment_4_1_1(), "rule__SJMethod__ParamsAssignment_4_1_1");
					put(grammarAccess.getSJMethodAccess().getBodyAssignment_6(), "rule__SJMethod__BodyAssignment_6");
					put(grammarAccess.getSJParameterAccess().getTypeAssignment_0(), "rule__SJParameter__TypeAssignment_0");
					put(grammarAccess.getSJParameterAccess().getNameAssignment_1(), "rule__SJParameter__NameAssignment_1");
					put(grammarAccess.getSJMethodBodyAccess().getStatementsAssignment_2(), "rule__SJMethodBody__StatementsAssignment_2");
					put(grammarAccess.getSJReturnAccess().getExpressionAssignment_1(), "rule__SJReturn__ExpressionAssignment_1");
					put(grammarAccess.getSJVariableDeclarationAccess().getTypeAssignment_0(), "rule__SJVariableDeclaration__TypeAssignment_0");
					put(grammarAccess.getSJVariableDeclarationAccess().getNameAssignment_1(), "rule__SJVariableDeclaration__NameAssignment_1");
					put(grammarAccess.getSJVariableDeclarationAccess().getExpressionAssignment_3(), "rule__SJVariableDeclaration__ExpressionAssignment_3");
					put(grammarAccess.getSJIfStatementAccess().getExpressionAssignment_2(), "rule__SJIfStatement__ExpressionAssignment_2");
					put(grammarAccess.getSJIfStatementAccess().getThenBlockAssignment_4(), "rule__SJIfStatement__ThenBlockAssignment_4");
					put(grammarAccess.getSJIfStatementAccess().getElseBlockAssignment_5_1(), "rule__SJIfStatement__ElseBlockAssignment_5_1");
					put(grammarAccess.getSJIfBlockAccess().getStatementsAssignment_0(), "rule__SJIfBlock__StatementsAssignment_0");
					put(grammarAccess.getSJIfBlockAccess().getStatementsAssignment_1_1(), "rule__SJIfBlock__StatementsAssignment_1_1");
					put(grammarAccess.getSJAssignmentAccess().getRightAssignment_1_2(), "rule__SJAssignment__RightAssignment_1_2");
					put(grammarAccess.getSJSelectionExpressionAccess().getMemberAssignment_1_2(), "rule__SJSelectionExpression__MemberAssignment_1_2");
					put(grammarAccess.getSJSelectionExpressionAccess().getMethodinvocationAssignment_1_3_0(), "rule__SJSelectionExpression__MethodinvocationAssignment_1_3_0");
					put(grammarAccess.getSJSelectionExpressionAccess().getArgsAssignment_1_3_1_0(), "rule__SJSelectionExpression__ArgsAssignment_1_3_1_0");
					put(grammarAccess.getSJSelectionExpressionAccess().getArgsAssignment_1_3_1_1_1(), "rule__SJSelectionExpression__ArgsAssignment_1_3_1_1_1");
					put(grammarAccess.getSJTerminalExpressionAccess().getValueAssignment_0_1(), "rule__SJTerminalExpression__ValueAssignment_0_1");
					put(grammarAccess.getSJTerminalExpressionAccess().getValueAssignment_1_1(), "rule__SJTerminalExpression__ValueAssignment_1_1");
					put(grammarAccess.getSJTerminalExpressionAccess().getValueAssignment_2_1(), "rule__SJTerminalExpression__ValueAssignment_2_1");
					put(grammarAccess.getSJTerminalExpressionAccess().getSymbolAssignment_6_1(), "rule__SJTerminalExpression__SymbolAssignment_6_1");
					put(grammarAccess.getSJTerminalExpressionAccess().getTypeAssignment_7_2(), "rule__SJTerminalExpression__TypeAssignment_7_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.example.smalljava.ui.contentassist.antlr.internal.InternalSmallJavaParser typedParser = (org.example.smalljava.ui.contentassist.antlr.internal.InternalSmallJavaParser) parser;
			typedParser.entryRuleSJProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SmallJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmallJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
