/**
 * generated by Xtext
 */
package org.example.expressions.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
@SuppressWarnings("all")
public class ExpressionsLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public ExpressionsLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
