/*
 * generated by Xtext
 */
package org.example.smalljava.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.example.smalljava.ui.internal.SmallJavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmallJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmallJavaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmallJavaActivator.getInstance().getInjector(SmallJavaActivator.ORG_EXAMPLE_SMALLJAVA_SMALLJAVA);
	}
	
}
