/*
* generated by Xtext
*/
package org.example.smalljava;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SmallJavaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.example.smalljava.ui.internal.SmallJavaActivator.getInstance().getInjector("org.example.smalljava.SmallJava");
	}
	
}
