/**
 * generated by Xtext
 */
package org.example.entities.ui.outline;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.example.entities.entities.Attribute;
import org.example.entities.entities.Entity;
import org.example.entities.entities.Model;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class EntitiesOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final Attribute a) {
    return true;
  }
  
  public void _createChildren(final DocumentRootNode outlineNode, final Model model) {
    EList<Entity> _entities = model.getEntities();
    final Procedure1<Entity> _function = new Procedure1<Entity>() {
      @Override
      public void apply(final Entity entity) {
        EntitiesOutlineTreeProvider.this.createNode(outlineNode, entity);
      }
    };
    IterableExtensions.<Entity>forEach(_entities, _function);
  }
}
