/*
 * generated by Xtext
 */
package org.example.smalljava;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.example.smalljava.scoping.SmallJavaImportedNamespaceAwareLocalScopeProvider;
import org.example.smalljava.scoping.SmallJavaResourceDescriptionsStrategy;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class SmallJavaRuntimeModule extends
		org.example.smalljava.AbstractSmallJavaRuntimeModule {

	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
				.to(SmallJavaImportedNamespaceAwareLocalScopeProvider.class);
	}
	
	/*
	 * If you enable this strategy, the NamesAreUniqueValidator will not
	 * work as expected.
	 */
	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return SmallJavaResourceDescriptionsStrategy.class;
	}
}
