/*
* generated by Xtext
*/
package org.example.smalljava;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SmallJavaStandaloneSetup extends SmallJavaStandaloneSetupGenerated{

	public static void doSetup() {
		new SmallJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

