/*
 * generated by Xtext
 */
package org.example.expressions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends org.example.expressions.AbstractExpressionsRuntimeModule {

}
